### ISSUE TITLE
Example of use case

### ISSUE THREAD

**Issue by JSousa-UoL** [tfmoraes/python-gdcm#1]
Your Python-GDCM package looks interesting. I assume the usage is mainly based on the official GDCM package and that the installation is based on setup.py, but would it be possible to demonstrate an example of how to use this in python please?

Something like this maybe?
import python-gdcm
method = python-gdcm.function(args), where args are the filenames and other GDCM flags

I might be completely wrong in the example, but that's why I'm asking to provide an example if possible please.

**Comment by tfmoraes** [comment]
Hi @JSousa-UoL. python-gdcm is just a packaging of GDCM. Any of this example will work https://github.com/malaterre/GDCM/tree/master/Examples/Python
