### ISSUE TITLE
gdcm.CryptoFactory.GetFactoryInstance() (line 95 in the example) returns nothing (NoneType object)

### ISSUE THREAD

**Issue by malaterre** [tfmoraes/python-gdcm#10]
Would be nice to document that the crypto stuff is not working on linux:

* https://sourceforge.net/p/gdcm/bugs/531/

Thanks !

**Comment by tfmoraes** [comment]
I'll try to build the wheels with the OpenSSL.

**Comment by tfmoraes** [comment]
@malaterre with this PR https://github.com/tfmoraes/python-gdcm/pull/11 the `GDCM` wheels are being created with `OpenSSL` support.
