### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by alexandreroutier** [tfmoraes/python-gdcm#16]
Hello,

Thank you very much for this work. I would like to use this tool but since your repo does not contain License file, [this involves that](https://choosealicense.com/no-permission/):

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Would it be possible to add a License to your project? e.g. the BSD License used by GCDM:
```
> cat GDCM/README.Copyright.txt
December 28, 2008

Historical note:

Starting with gdcm 2.0.11, GDCM, Grassroots DICOM is distributed
under the new simplified BSD license, approved by the Open Source Initiative (OSI)
* http://www.opensource.org/licenses/bsd-license.php

See Copyright.txt
```

Best,
Alexandre

**Comment by tfmoraes** [comment]
Hi @alexandreroutier, I added a license to this repo https://github.com/tfmoraes/python-gdcm/blob/master/LICENSE

**Comment by alexandreroutier** [comment]
Thank you very much! :)

Best,
Alexandre
