### ISSUE TITLE
64-bit ARM wheels

### ISSUE THREAD

**Issue by taleinat** [tfmoraes/python-gdcm#17]
Would it be possible to provide binary wheels for 64-bit ARM (a.k.a. "aarch64") Linux?

I see that such wheels are already provided for 64-bit ARM macOS and x86-64 & i686 Linux, so hopefully not too difficult to do...

**Comment by tfmoraes** [comment]
I'll try to set the Github CI to build to aarch64 on Linux.

**Comment by tfmoraes** [comment]
@taleinat I submitted the aarch64 wheels to pypi.

**Comment by taleinat** [comment]
Wow @tfmoraes, fantastic that you could do this so quickly, many thanks!

I'll test this soon.

**Comment by taleinat** [comment]
Running in a Linux container on an M1 Mac, python-gdcm now installs without issues and seems to be working as expected.

:+1::+1:
