### ISSUE TITLE
GDCM build applications - can they be included in PyPI?

### ISSUE THREAD

**Issue by JSousa-UoL** [tfmoraes/python-gdcm#2]
I'm a bit familiar with the GDCM package [here](https://github.com/malaterre/GDCM/tree/master). 

What you're doing is allowing an easy install with pip using GDCM API for Python? Correct me if I'm wrong.

A popular use of GDCM is running its command-line applications such as `gdcminfo`, `gdcmdump`, ..., etc. (See [here](https://github.com/malaterre/GDCM/tree/master/Applications/Cxx)). 

My big question is: Is there a way to have these available in Python? Is it possible to build them during pip install? I can see you use some cmake flags in the `setup.py` file. For these applications to be available you would have to set the flag "-DGDCM_BUILD_APPLICATIONS:BOOL=OFF" to ON. Would that be enough or is it a lot more complex?

**Comment by tfmoraes** [comment]
If you set `-DGDCM_BUILD_APPLICATIONS:BOOL` to `ON` it will build all the gdcm applications. It's necessary to all the applications in the correct folder and change the link paths to link correctly with libs the site-packages.  I don't know how complex is that.

**Comment by JSousa-UoL** [comment]
I see, it's likely that it'll be complex. It's something that you could try if you have time.
You can close this if you want to. I used this issues mechanism as a way to contact you and to have it recorded here on Github in case anyone is searching for the same things.

**Comment by tfmoraes** [comment]
@JSousa-UoL I created a PR to include GDCM applications in the wheel. Please, try to test it.
