### ISSUE TITLE
Security warning on latest update

### ISSUE THREAD

**Issue by Renal-Of-Loon** [tfmoraes/python-gdcm#21]
Hello,

I'm really not certain if this is an overzealous antivirus issue or a genuine concern, but I figured I'll bring it up here.

I tried installing the latest version (`python-gdcm==3.0.24`) and had my antivirus (Bitdefender) spit out the following alert:

```
The file <filepathCensor>\venv\Lib\site-packages\_gdcm\gdcmtar.exe is infected with Gen:Variant.Lazy.478582 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean
```

I did *not* have this issue with `python-gdcm==3.0.23.1` when testing right after.

I do not have the skillset to figure out if this is a legitimate issue or not, but hopefully someone can at least take a look at it.

Cheers

**Comment by tfmoraes** [comment]
Hi,

That's strange. The  packages are generated in Github CI. I tried here in Windows and Microsoft Defender didn't detect any virus. I'll try to check this.

Best regards.

**Comment by tfmoraes** [comment]
Using windows-2019 instead of windows-latest seems to fix this problem.

**Comment by tfmoraes** [comment]
I pushed a new version (3.0.24.1) and it seems to fix this problem. I tested with [virustotal](https://www.virustotal.com) and nothing was detected. Please, test it.

**Comment by Renal-Of-Loon** [comment]
3.0.24.1 installed with no alerts on my end, and was not flagged when manually scanning the folder.

I appreciate the speedy response and action on this; thank you kindly!

**Comment by tfmoraes** [comment]
Thanks! Closing this issue.
