### ISSUE TITLE
install in python:3.6-alpine image failed

### ISSUE THREAD

**Issue by summy00** [tfmoraes/python-gdcm#4]
![image](https://user-images.githubusercontent.com/9530193/113657434-8265b680-96d0-11eb-9305-67651c3d5613.png)

**Comment by tfmoraes** [comment]
@summy00 you need to install swig and ninja before.

**Comment by summy00** [comment]
> @summy00 you need to install swig and ninja before.

I have installed by:
```
apk add swig

git clone -b 'release' --depth=1 https://github.com/ninja-build/ninja.git
cd ninja
./configure.py --bootstrap
cmake -Bbuild-cmake -H.
cmake --build build-cmake

git clone https://github.com/tfmoraes/python-gdcm.git
cd python-gdcm

```
but still error:
![image](https://user-images.githubusercontent.com/9530193/113715474-1f017600-971c-11eb-9da8-845f04afb499.png)

maybe I not install swig & ninja successfully

**Comment by tfmoraes** [comment]
Try to export CMAKE_EXE and SWIG_EXE before the building:

```
$ export CMAKE_EXE=/CMAKE/PATH
$ export SWIG_EXE=/SWIG/PATH
```

**Comment by summy00** [comment]
> Try to export CMAKE_EXE and SWIG_EXE before the building:
> 
> ```
> $ export CMAKE_EXE=/CMAKE/PATH
> $ export SWIG_EXE=/SWIG/PATH
> ```

already done

**Comment by tfmoraes** [comment]
I managed to compile this way:

```
apk add swig ninja cmake gcc g++ patchelf
pip install python-gdcm
```

It compiles but doesn't import gdcm:

```
$ python -c "import gdcm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/python-gdcm/gdcm.py", line 62, in <module>
    from _gdcm.gdcmswig import *
ModuleNotFoundError: No module named '_gdcm.gdcmswig'
```

**Comment by summy00** [comment]
after I change `-SWIG_EXECUTABLE` to `-DSWIG_EXECUTABLE`, and update submodule, it prompts:
![image](https://user-images.githubusercontent.com/9530193/113725633-1615a200-9726-11eb-9a07-d5ab9d56599d.png)

**Comment by summy00** [comment]
after I run `apk add ninja` it can cmake with Ninja now...
and can build with `python setup.py install`, I will test it if it can `import gdcm`

**Comment by summy00** [comment]
build success, but cannot import
![image](https://user-images.githubusercontent.com/9530193/113730063-216acc80-972a-11eb-9e4a-f954e756765f.png)

**Comment by tfmoraes** [comment]
Exporting to `LD_LIBRARY_PATH` makes it work:

```shell
$ export LD_LIBRARY_PATH="/usr/local/lib"
$ python -c "import gdcm; print(gdcm.Version().GetVersion())"
3.0.8
```

I don't know why but "/usr/local/lib" is not in path list to find the shared libraries. But you can fix it exporting `LD_LIBRARY_PATH`.

**Comment by tfmoraes** [comment]
So to install `python-gdcm` in `python:3.6-alpine` you have to run the following commands:

```shell
# Install swig, ninja, cmake, gcc, c++, patchelf
$ apk add swig ninja cmake gcc g++ patchelf

# Install python-gdcm
$ pip install python-gdcm

# export LD_LIBRARY_PATH to make system find `libpython.so`
$ export LD_LIBRARY_PATH="/usr/local/lib"

# Run Python, import GDCM and print GDCM version
python -c "import gdcm; print(gdcm.Version().GetVersion())"
```

**Comment by summy00** [comment]
thanks
