### ISSUE TITLE
Error installing with Docker using ubuntu:20.04 as base

### ISSUE THREAD

**Issue by jwn8175** [tfmoraes/python-gdcm#6]
I am installing several packages using pip as such `pip3 install pillow pydicom ...`. But when I do `pip3 install python-gdcm` I get an error. I have included the logs in a txt file.

![image](https://user-images.githubusercontent.com/39040834/125872419-9d2c8c16-ade2-44ca-82c1-9e83c520313d.png)

[install-log.txt](https://github.com/tfmoraes/python-gdcm/files/6826816/install-log.txt)

**Comment by tfmoraes** [comment]
It seems to me that your system doesn't have Cmake installed. Also, you have to install Ninja build and Swig.

**Comment by jwn8175** [comment]
Will give that a try, thank you.
