### ISSUE TITLE
Add wheels for Windows with Python 3.10

### ISSUE THREAD

**Issue by scaramallion** [tfmoraes/python-gdcm#7]
Hi, do you mind adding wheels for Windows with Python 3.10?

Thanks!

**Comment by tfmoraes** [comment]
Hi @scaramallion. When I generated the last wheels I wasn't able to compile GDCM using Python 3.10 on Windows. I'll try to compile it again.

**Comment by scaramallion** [comment]
That does sound like a pickle. No problem if it doesn't work.

**Comment by tfmoraes** [comment]
I tried to compile compile GDCM using Python 3.10 on Windows but it gives an error on the linker phase.

**Comment by scaramallion** [comment]
OK thanks. I might have a play around with it if I get a chance.
